### ISSUE TITLE
Reflect the collection status in README, disable CI tests

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.sap#24]
### Summary

@rainerleber can we
- reflect in README that the collection is deprecated and is superseded by another collection?
- disable tests?

If yes, could you please raise a PR?

### Issue Type

Documentation Report

### Component Name

README

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.sap

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by rainerleber** [comment]
Hi @Andersson007  yes i will take care of it. Should we also add the migration like describe here ? https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_migrating.html

**Comment by Andersson007** [comment]
@rainerleber sure (I would use the [devel version](https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_migrating.html#migrating-ansible-content-to-a-different-collection) of the doc) but be careful with the stuff that require planning, preparatory work and major releases.
If you have any questions along the way, please ask the community in https://matrix.to/#/#community:ansible.com.

When you're done with README and the tests, please let me know, thanks!

**Comment by rainerleber** [comment]
Done ;-) PR is open

**Comment by Andersson007** [comment]
closed via https://github.com/ansible-collections/community.sap/pull/25
thanks @rainerleber !
