### ISSUE TITLE
To run SAP task lists with a variant

### ISSUE THREAD

**Issue by joanba68** [ansible-collections/community.sap#30]
### Summary

We're automating the bootstraping of an SAP application server with ansible and DevOps. We're able to create the server, install OS, install SAP application instance with SWPM, update profiles and restart it. To finish this initial setup we want to run a task list we've created in the SAP system using community.sap_libs.sap_task_list_execute module but it looks like there is no option to specify a variant. I see it's possible to pass parameters to an specific step, but in our case we should run the step twice so how to identify each one. As example, these are two steps:

CL_STCT_CREATE_LOGONGROUP --> with defaults to add server in PUBLIC logon group and parallel_generators RFC group
CL_STCT_CREATE_LOGONGROUP --> to add to an additional RFC server named 390

Any idea ? 

### Issue Type

Feature Idea

### Component Name

community.sap ansible module

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by rainerleber** [comment]
@joanba68 Thank you for opening the issue. This collection is closed and migrated. Could you please migrate/reopen the Issue to/on the new location: https://github.com/sap-linuxlab/community.sap_libs
